# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Stock Analysis

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
		pip install pystan
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Stock Analysis & update readme for showing prediction result
      run: |
        python stock_analysis.py
        git diff
        git config --global user.email "cheehoon12@hanmail.net"
        git config --global user.name "cheesama"
        git add -A
        git commit -m "Updated README content" || exit 0
        git push
      env:
        FULL_ACCESS_TOKEN: ${{ secrets.FULL_ACCESS_TOKEN }}

