# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Stock Analysis

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Stock Analysis
      run: |
        python stock_analysis.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo "::set-env UPLOAD_CONTENTS=UPLOAD_CONTENTS::$UPLOAD_CONTENTS"
    - run: echo $UPLOAD_CONTENTS
    - name: Create Issue for stock prediction result
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Stock Prediction Result {{ date | date('dddd, MMMM Do') }}
        token: ${{secrets.GITHUB_TOKEN}}
        body: ${{ echo $UPLOAD_CONTENTS }}
      
    - name: Update Stock Prediction result to README
      uses: theboi/github-update-readme@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        header: "Korean Stock Prediction Result"
        subhead: "$(echo $UPLOAD_CONETENTS)"
        footer: "$(date +'%Y-%m-%d')"

